version: "3"
networks:
  network_mysql:
    external: true

services:
  db:
    image: mysql:8-debian
    container_name: mysql-master
    networks:
      - network_mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_HOSTS=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sungil
      - MYSQL_PASSWORD=sungil
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/mysql:/var/lib/mysql