project-info:
  name: SPT Framework Web Core
  version: v1.0.0
  description : enjoy your coding life with SPT Framework Web Core

server:
  port: 443

spring:
  devtools:
    livereload.enabled: true
    restart.enabled: true

  config:
    import:
      #_frameworkWebCoreResources
      - optional:classpath:_autoSqlInitialize/autoSqlInitialize.yml
      - optional:classpath:_frameworkWebCoreResources/_frameworkApplicationProperties/globalError/globalError.yml
      - optional:classpath:_frameworkWebCoreResources/_frameworkApplicationProperties/h2DB/h2DB.yml
      - optional:classpath:_frameworkWebCoreResources/_frameworkApplicationProperties/jsp/jsp.yml
      - optional:classpath:_frameworkWebCoreResources/_frameworkApplicationProperties/pageHelper/pageHelper.yml
      - optional:classpath:_frameworkWebCoreResources/_frameworkApplicationProperties/ssl/ssl.yml
      - optional:classpath:_frameworkWebCoreResources/_frameworkApplicationProperties/thymeleaf/thymeleaf.yml
      #_projectCommonResources(_system)
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_framework/cors/corsPolicy.yml
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_framework/datasource/datasource.yml
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_framework/encryption/encryption.yml
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_framework/jpa/jpa.yml
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_framework/jwt/jwt.yml
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_framework/logging/logging.yml
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_framework/session/session.yml
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_framework/springdoc/springdoc.yml
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_framework/_frameworkOption/frameworkOption.yml
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_framework/storage/storage.yml
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_framework/globalStaticViewModel/globalStaticViewModel.yml
      #_projectCommonResources(extra)
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/example1/example1.yml

