project-info:
  name: myProject
  version: v1
  description : Local


system:
  propertySources:
    expose-enabled: ture #스프링 스타트시 시스템 property를 로그로 보여줄지 설정


server:
  port: 8443
  servlet.session:
    timeout: 60m
    cookie:
      name: JSESSIONID
      http-only: true
      secure: true #(ssl 사용시 설정과 상관없이 true로 설정됨, ssl 비사용시 false로 설정할수 있으나 false 일경우 브라우저가 자체 block처리하여 사용이 불가능함)
      same-site: none #(사설 인증서의 경우 Lax 사용을 해도 브라우저가 block 처리함, 테스트를 위해 none 설정 필요)
  #사설 인증사의 경우 로컬 테스트를 위해 브라우저 설정 필요 (chrome://flags/ -> Allow invalid certificates for resources loaded from localhost. -> Enabled, 도메인은 front.localhost:8080 형태로 구성)
  ssl:
    key-store: classpath:keystore/keystore.p12
    key-store-type: PKCS12
    key-store-password: keystore_password
  #에러전파순서 :
  #개발자가만든 ExHandler가 1순위 (여기서 처리가 안되면)
  #   --> 스프링 에러 처리 메커니즘  (특정위치에 404.html, 5xx.html 과 같이 페이지를 만들어 놓으면 에러코드에 따라 해당 페이지 호출해줌, 페이지가 없으면 기본폼(whitelabel)으로 호출됨, 에러 파일도 없고 whitelabel.enabled: false 이면 was에러 페이지로 넘김)
  #     --> WAS 에러 페이지 (스프링 내부에서 처리하지 못하면 was가 제공하는 기봄폼으로 노출)
  error: #스프링에서 제공하는 에러 기본 처리 설정
    include-exception: true #exception 정보를 보여줄지
    include-stacktrace: always #stacktrace 를 보여줄지
    path: error #에러 처리에 대한 뷰 경로
    whitelabel.enabled: false #스프링의 기본 에러 페이지(Whitelabel Error Page)를 사용할지


Storage:
  multipartFiles:
    basePath: c:/


logging:
  level: #log level은 logback config 파일에 그대로 반영됨
    root: info
    com:
      sptek.webfw: debug
      zaxxer.hikari.pool.HikariPool: info
    org:
      mybatis.spring: info
      springframework: info
    jdbc:
      audit: info
      resultset: info
      resultsettable: debug #INFO  #SQL 결과 데이터 Table을 로그로 남긴다.
      sqlonly: info     #SQL만 로그로 남긴다.
      sqltiming: info    #SQL과 소요시간을 표기한다.
      connection: info  # 커넥션 확인가능
  config: classpath:logbackConfig/logback-spring-local.xml


spring:
  web:
    resources:
      static-locations: #static resource 에 대한 디폴트 경로 및 표기를 지정함(여러 모양으로 지정가능), 설정이 없다면 resource/static/xxx 를 /xxx로 접근할수 있음
        - classpath:/resources/ #/resource/static/xxx 를 /xxx로 접근함 (디폴트 설정과 같은 내용, 근데 이게 없으면 resource/favicon.ico 가 404가 나는 문제가 있어서 추가함)
        - classpath:/static/ #/resource/static/xxx 를 /static/xxx로 접근함
  devtools: #코드 수정 실시간 반영
    livereload:
      enabled: true
    restart:
      enabled: true
  config:
    import: #기본 프로퍼티가 아닌 추가적인 property 파일로 구성 필요시.
      - classpath:specificProperties/specificName.yml
      - classpath:specificProperties/secureOption.yml
  thymeleaf:
    enabled: true
    cache: false
    check-template-location: true
    #prefix: classpath:/templates/thymeleaf/ #이렇게 설정하면 로컬서버에서 실행중 실시간 수정 변경이 안되는 현상이 있음
    prefix: file:src/main/resources/templates/thymeleaf/
    suffix: .html
  #jsp로 설정할때
  #mvc:
  #  view:
  #    prefix: /WEB-INF/views/
  #    suffix: .jsp
  h2: #H2 임베드 DB 사용은 프로퍼티설정만 있음
    console:
      enabled: true #웹콘솔 사용 여부
      path: /h2-console #웹콘솔 url 경로, ex:https://localhost:8443/h2-console/
  datasource: #리플리카 구성이 아닌 단순 DS 사용
    #메모리 모드로 실행됨 (휘발성, @Entity 클레스에 대해 자동으로 TB 구성, schema.sql, data.sql 자동 실행)
    #url: jdbc:h2:mem:myDB
    #서버 모드(파일)로 실행됨(최초에 해당 위치에서 cmd로 copy con local.mv.db 를 통해 초기 DB파일 생성 필요, 저장된 DB로 이어서 실행됨)
    url: jdbc:h2:file:./data/h2/myDB;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update #(create, create-drop, update, none)
  sql:
    init:
      mode: always #삭제후초기화(always, never, embedded)
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql


#PageInoSupport 클레스 관련 설정
pagehelper:
  helper-dialect: mysql
  auto-dialect: true
  page-size-zero: false
  reasonable: true
  offset-as-page-num: false
  row-bounds-with-count: false
  auto-runtime-dialect: false
  close-conn: true
  default-count: true


jasypt:
  encryptor:
    bean=encryptorBean: jasyptStringEncryptor
    secretKey: JasyptStringEncryptor_key_Hello


# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.sptek.webfw.example.api.api1
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html         # Swagger UI 경로 => https://localhost:8080/swagger-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true