project-info:
  name: SPT Framework Web Core
  version: v1.0.0
  description : enjoy your coding life with SPT Framework Web Core

server:
  port: 443

spring:
  devtools:
    livereload.enabled: true
    restart.enabled: true

  config:
    import:
      #_frameworkWebCoreResources
      - optional:classpath:_autoSqlInitialize/autoSqlInitialize.yml
      - optional:classpath:_frameworkWebCoreResources/_frameworkApplicationProperties/globalError/globalError.yml
      - optional:classpath:_frameworkWebCoreResources/_frameworkApplicationProperties/h2DB/h2DB.yml
      - optional:classpath:_frameworkWebCoreResources/_frameworkApplicationProperties/jsp/jsp.yml
      - optional:classpath:_frameworkWebCoreResources/_frameworkApplicationProperties/pageHelper/pageHelper.yml
      - optional:classpath:_frameworkWebCoreResources/_frameworkApplicationProperties/ssl/ssl.yml
      - optional:classpath:_frameworkWebCoreResources/_frameworkApplicationProperties/thymeleaf/thymeleaf.yml
      #_projectCommonResources(_system)
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_system/cors/corsPolicy.yml
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_system/datasource/datasource.yml
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_system/encryption/encryption.yml
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_system/jpa/jpa.yml
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_system/jwt/jwt.yml
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_system/logging/logging.yml
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_system/session/session.yml
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_system/springdoc/springdoc.yml
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_system/_frameworkOption/frameworkOption.yml
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_system/storage/storage.yml
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/_system/globalModelAttribute/globalModelAttribute.yml
      #_projectCommonResources(extra)
      - optional:classpath:_projectCommonResources/_projectApplicationProperties/example1/example1.yml

