project-info:
  name: myProject
  version: v1
  description : sptek web framework

server:
  port: 8080

  error:
    include-exception: true
    include-stacktrace: always
    path: error
    whitelabel.enabled: false

spring:
  profiles:
    active: local


  thymeleaf:
    cache: false
    prefix: classpath:/templates/thymeleaf/
    suffix: .html
    enabled: true

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.sptek.webfw.example.api.api1
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html            # Swagger UI 경로 => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true