server:
  port: 8443

extraApplicationProperties:
  basePath:
    frameworkWebCore: classpath:_frameworkWebCoreResources/extraApplicationProperties/
    projectCommon: classpath:_projectCommonResources/extraApplicationProperties/

spring.devtools:
  livereload.enabled: true
  restart.enabled: true

