project-info:
  name: myProject
  version: v1
  description : sptek web framework


server:
  port: 8080
  error:
    include-exception: true
    include-stacktrace: always
    path: error
    whitelabel.enabled: false


logging:
  level:
    com:
      zaxxer:
        hikari:
          pool:
            HikariPool: debug
    org:
      mybatis:
        spring: debug
    jdbc:
      audit: OFF
      resultset: OFF
      resultsettable: INFO  #SQL 결과 데이터 Table을 로그로 남긴다.
      sqlonly: OFF     #SQL만 로그로 남긴다.
      sqltiming: INFO    #SQL과 소요시간을 표기한다.
      connection: OFF  # 커넥션 확인가능



spring:
  profiles:
    active: local

  datasource:
    write:
      #driver-class-name: com.mysql.cj.jdbc.Driver
      #jdbc-url: jdbc:mysql://localhost:3306/bookclub?serverTimezone=UTC
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/bookclub?serverTimezone=UTC
      username: root
      password: root
      pool-name: Hikari master Connection Pool
      maximum-pool-size: 20
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
    read:
      #driver-class-name: com.mysql.cj.jdbc.Driver
      #jdbc-url: jdbc:mysql://localhost:3306/bookclub?serverTimezone=UTC
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3307/bookclub?serverTimezone=UTC
      username: root
      password: root
      pool-name: Hikari slave Connection Pool
      maximum-pool-size: 20
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000

#  mvc:
#    view:
#      prefix: /WEB-INF/views/
#      suffix: .jsp

  thymeleaf:
      cache: false
      prefix: classpath:/templates/thymeleaf/
      suffix: .html
      enabled: true


pagehelper:
  helper-dialect: mysql
  auto-dialect: true
  page-size-zero: false
  reasonable: true
  offset-as-page-num: false
  row-bounds-with-count: false
  auto-runtime-dialect: false
  close-conn: true
  default-count: true

# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.sptek.webfw.example.api.api1
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html            # Swagger UI 경로 => localhost:8000/demo-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true

