project-info:
  name: myProject Local
  version: v1
  description : sptek web framework

spring:
  config:
    import:
      - classpath:specificProperties/specificName.yml

logging:
  level:
    com.sptek.webfw: DEBUG

