server:
  port: 8443

spring:
  devtools:
    livereload.enabled: true
    restart.enabled: true

  config:
    import:
      #_frameworkWebCoreResources
      - optional:classpath:_frameworkWebCoreResources/extraApplicationProperties/autoInitializeDB/autoInitializeDB.yml
      - optional:classpath:_frameworkWebCoreResources/extraApplicationProperties/globalError/globalError.yml
      - optional:classpath:_frameworkWebCoreResources/extraApplicationProperties/h2DB/h2DB.yml
      - optional:classpath:_frameworkWebCoreResources/extraApplicationProperties/jsp/jsp.yml
      - optional:classpath:_frameworkWebCoreResources/extraApplicationProperties/pageHelper/pageHelper.yml
      - optional:classpath:_frameworkWebCoreResources/extraApplicationProperties/ssl/ssl.yml
      - optional:classpath:_frameworkWebCoreResources/extraApplicationProperties/thymeleaf/thymeleaf.yml
      #_projectCommonResources(_system)
      - optional:classpath:_projectCommonResources/extraApplicationProperties/_system/cors/
      - optional:classpath:_projectCommonResources/extraApplicationProperties/_system/datasource/datasource.yml
      - optional:classpath:_projectCommonResources/extraApplicationProperties/_system/encryption/encryption.yml
      - optional:classpath:_projectCommonResources/extraApplicationProperties/_system/jpa/jpa.yml
      - optional:classpath:_projectCommonResources/extraApplicationProperties/_system/jwt/jwt.yml
      - optional:classpath:_projectCommonResources/extraApplicationProperties/_system/logging/logging.yml
      - optional:classpath:_projectCommonResources/extraApplicationProperties/_system/session/session.yml
      - optional:classpath:_projectCommonResources/extraApplicationProperties/_system/springdoc/springdoc.yml
      - optional:classpath:_projectCommonResources/extraApplicationProperties/_system/sptFramework/sptFramework.yml
      - optional:classpath:_projectCommonResources/extraApplicationProperties/_system/storage/storage.yml
      #_projectCommonResources(extra)
      - optional:classpath:_projectCommonResources/extraApplicationProperties/example1/example1.yml

