server:
  port: 8443

extraApplicationProperties:
  basePath:
    - classpath:_frameworkWebCoreResources/extraApplicationProperties/
    - classpath:_projectCommonResources/extraApplicationProperties/

spring.devtools:
  livereload.enabled: true
  restart.enabled: true