spring:
  datasource:
    #write, read로 리플리케이션 구조 설정
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver #(디폴트)
      jdbc-url: jdbc:mysql://localhost:3306/spt_web_fw?serverTimezone=UTC
      #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      #jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/spt_web_fw?serverTimezone=UTC
      username: sptek
      password: ENC(/Ylid4X1rWuhuuo+FUfo0QjXWXdPROMxoYh3JQ916zpfkotbS3rGcWQWMfKYALCc)
      pool-name: Hikari write Connection Pool
      maximum-pool-size: 20
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver #(디폴트)
      jdbc-url: jdbc:mysql://localhost:3307/spt_web_fw?serverTimezone=UTC
      #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      #jdbc-url: jdbc:log4jdbc:mysql://localhost:3307/spt_web_fw?serverTimezone=UTC
      username: sptek
      password: ENC(/Ylid4X1rWuhuuo+FUfo0QjXWXdPROMxoYh3JQ916zpfkotbS3rGcWQWMfKYALCc)
      pool-name: Hikari read Connection Pool
      maximum-pool-size: 20
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000