### 존재하지 않는 URL (/xxx)
GET {{api-server-ver}}/xxx
Content-Type: text/html

### 존재하지 않는 Request method (Post만 존재)
GET {{api-server-ver}}/example/responseError/a/dtoValidation
Content-Type: text/html

### 존재하지 않는 Content-Type (Post만 존재)
POST {{api-server-ver}}/example/responseError/a/dtoValidation
Content-Type: text/html

### Body 가 존재하지 않는 잘못된 요청
POST {{api-server-ver}}/example/responseError/a/dtoValidation
Content-Type: application/json

#### 정상 호출
POST {{api-server-ver}}/example/responseError/a/dtoValidation
Content-Type: application/json

{
  "userId": "sungilry",
  "userName": "이성일",
  "age": 20,
  "email": "sungilry@sptek.co.kr",
  "mobileNumber": "01012345678"
}