### view Test
GET {{web-server}}/welcome
Content-Type: text/html

### view Test
POST {{web-server}}/welcomeGet
Content-Type: text/html

### view Test
POST {{web-server}}/welcomePost
Content-Type: text/html

### view Test
POST {{web-server}}/xssTest?message=<script>
Content-Type: text/plain

abcde:abd



### hello
GET {{api-server-ver}}/hello?message=hi
Content-Type: application/json

### helloGet
GET {{api-server-ver}}/helloGet?message=hi
Content-Type: application/json

### helloGet
POST {{api-server-ver}}/helloGet?message=hi
Content-Type: application/json

### helloPost
POST {{api-server-ver}}/helloPost?message=hi
Content-Type: application/json

{
  "abc": "abc"
}

### hello
GET {{api-server-ver}}/testJpa
Content-Type: application/json


### apiServiceError
GET {{api-server-ver}}/apiServiceError?errorCaseNum=1
Content-Type: application/json


### jasyptEnc 테스트
POST {{web-server}}/public/jasyptEnc
Content-Type: text/html

originPlainText

### jasyptDec 테스트
POST {{web-server}}/public/jasyptDec
Content-Type: text/html

KvF6T1vmnpuch4OqqLci0TNRpr49EiCFYG6zkQU8FbXheNP4z7VfYgQg/yEygNqC

### aesEnc 테스트
POST {{web-server}}/public/aesEnc
Content-Type: text/html

originPlainText

### aesDec 테스트
POST {{web-server}}/public/aesDec
Content-Type: text/html

+qyH9/BjtEIGy0BJ8Lm0/ApuBoYD7oovvR2va5MAJYk=

### desEnc 테스트
POST {{web-server}}/public/desEnc
Content-Type: text/html

originPlainText

### desDec 테스트
POST {{web-server}}/public/desDec
Content-Type: text/plain

6xQHOBfp1u2+Kjd8c5KHn3o/sS20KrFw

> {%
//동적 변수 set 테스트
const eTag = response.headers.valueOf("ETag");
if (eTag) {
    client.global.set("eTag", eTag);
    client.log("set eTag: " + client.global.get("eTag"));
} else {
    client.log("eTag not found in header");
}
%}
### 서버정보
GET {{api-server-ver}}/projectinfo
Content-Type: application/json



### XssProtectSupport 테스트
GET {{api-server-ver}}/XssProtectSupportGet?originText=<javascript>alert('hello');</javascript>
Content-Type: application/json

### XssProtectSupport 테스트
POST {{api-server-ver}}/XssProtectSupportPost
Content-Type: application/json

{
  "originText": "<javascript>alert('hello');</javascript>"
}

### interceptor 테스트
GET https://back.localhost:8080/api/v1/interceptor
Content-Type: application/json

### interceptor 테스트
GET https://back.localhost:8080/api/v2/interceptor
Content-Type: application/json

### interceptor 테스트
PUT https://back.localhost:8080/api/v1/interceptor
Content-Type: application/json

### interceptor 테스트
DELETE https://back.localhost:8080/api/v1/interceptor
Content-Type: application/json



### httpCache?c=c 테스트
GET {{api-server-ver}}/httpCache?c=c
Content-Type: application/json

### httpCache?c=c 테스트
POST {{api-server-ver}}/httpCache?c=c
Content-Type: application/json

### httpCache?c=c 테스트
PUT {{api-server-ver}}/httpCache?c=c
Content-Type: application/json

### httpCache?c=c 테스트
PATCH {{api-server-ver}}/httpCache?c=c
Content-Type: application/json



### closeableHttpClient 테스트
GET {{api-server-ver}}/closeableHttpClient
Content-Type: application/json

### closeableHttpClientSupport 테스트
POST {{api-server-ver}}/closeableHttpClientSupport
Content-Type: application/json

### restTemplate 테스트
GET {{api-server-ver}}/restTemplate
Content-Type: application/json

### restTemplateSupport 테스트
GET {{api-server-ver}}/restTemplateSupport
Content-Type: application/json

### reqResUtil 테스트
POST {{api-server-ver}}/reqResUtil?a=1&b=2&a=3
Content-Type: application/json



### validationAnnoTationt Post 테스트
POST {{api-server-ver}}/validationAnnotationPost
Content-Type: application/json

{
  "userId": "sungilry",
  "userName": "sungil",
  "age": 10,
  "email": "sungilrynaver.com",
  "mobileNumber" : "01042983113"
}

### validationAnnoTationt Get 테스트
GET {{api-server-ver}}/validationAnnotationGet?userId=sungilry&userName=sungilry&age=43&email=sungilry%40naver.com&mobileNumber=01042983113
Content-Type: application/json



### property 테스트
GET {{api-server-ver}}/propertyConfigImport
Content-Type: application/json



### customMyUserHandler 테스트
GET {{api-server-ver}}/argumentResolverForMyUser?id=admin
Content-Type: application/json

### customMyUserHandler2 테스트1
GET {{api-server-ver}}/argumentResolverForMyUser2?id=admin
Content-Type: application/json

### customMyUserHandler2 테스트2
GET {{api-server-ver}}/argumentResolverForMyUser2?id=sungil
Content-Type: application/json



### duplicatedRequest 테스트
GET {{api-server-ver}}/duplicatedRequest
Content-Type: application/json

### duplicatedRequest 테스트2
POST {{api-server-ver}}/duplicatedRequest
Content-Type: application/json

### duplicatedRequest 테스트(View)
GET {{web-server}}/duplicatedRequest
Content-Type: text/html

### duplicatedRequest 테스트2(View)
POST {{web-server}}/duplicatedRequest
Content-Type: text/html


### Security ---------------------------------
### API 방식 인증 요청 테스트
POST {{api-server-ver}}/login
Content-Type: application/json

{
  "username": "sungilry1@naver.com",
  "password": "1q2w3e4r5t!Q"
}
> {%
    client.global.set("jwt", response.body.result);
%}

### 테스트
GET {{api-server-ver}}/public/hello
Content-Type: application/json


### 테스트
GET {{api-server-ver}}/user/hello
Authorization: Bearer {{jwt}}
Content-Type: application/json

### 테스트
GET {{api-server-ver}}/auth/hello?a=a
Authorization: Bearer {{jwt}}
Content-Type: application/json

### 테스트
GET {{api-server-ver}}/admin/anyone
Authorization: Bearer {{jwt}}
Content-Type: application/json

### 테스트
GET {{api-server-ver}}/admin/marketing
Authorization: Bearer {{jwt}}
Content-Type: application/json

### 테스트
GET {{api-server-ver}}/admin/delivery
Authorization: Bearer {{jwt}}
Content-Type: application/json

### 테스트
GET {{api-server-ver}}/system/anyone
Authorization: Bearer {{jwt}}
Content-Type: application/json

### 테스트
GET {{api-server-ver}}/public/anyone/butNeedControllRole
Authorization: Bearer {{jwt}}
Content-Type: application/json

### 테스트
GET {{api-server-ver}}/public/anyone/butNeedFilterAuth
Authorization: Bearer {{jwt}}
Content-Type: application/json

### 테스트
GET {{api-server-ver}}/public/anyone/butNeedControllAuth
Authorization: Bearer {{jwt}}
Content-Type: application/json

### 테스트
GET {{api-server-ver}}/public/postPutAfterAuth
Authorization: Bearer {{jwt}}
Content-Type: application/json

### 테스트
GET {{api-server-ver}}/exampleEvent
Authorization: Bearer {{jwt}}
Content-Type: application/json