spring:
  sql:
    init:
      mode: always #(always, never, embedded)
      schema-locations: classpath:_projectCommonResources/_initialDB/schema*.sql
      data-locations: classpath:_projectCommonResources/_initialDB/data*.sql