spring:
  thymeleaf:
    enabled: true
    cache: false #html 실시간 반영을 위해서는 false 처리
    check-template-location: true
    prefix: classpath:/templates/thymeleaf/ #서버에서는 반드시 이설정으로..
    #prefix: file:src/main/resources/templates/thymeleaf/ #로컬에서 개발중 실시간 반영을 위해
    mode: HTML
    suffix: .html
    encoding: UTF-8

